### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyter-remote-desktop-proxy#115]
The image tests are failing, but the bash is too complex for me to really debug. I think it's ok for now.

**Comment by manics** [comment]
I don't think it's the tests, I think there's a genuine error. A clean rebuild of `main` leads to the desktop failing to appear, and a Javascript error `Uncaught Error: Cannot find module '@novnc/novnc/core/rfb'`

**Comment by manics** [comment]
Hmmm.... maybe there are multiple errors, https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/120 is still failing

**Comment by consideRatio** [comment]
Did a new version of websockify arrive 1 month ago perhaps? Tests fail when websockify is involved, but for both tiger and turbovnc, and in a test without this project proxying things involved.

**Comment by manics** [comment]
I've removed websockify: https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/119
