### ISSUE TITLE
Unable to use Desktop with TurboVNC, using latest image, via apptainer

### ISSUE THREAD

**Issue by psobolewskiPhD** [jupyterhub/jupyter-remote-desktop-proxy#128]
### Bug description

I'm running the docker container using apptainer/singularity (1.1.9) on a Rocky9 HPC cluster.
This works, I can access Jupyter just fine using the browser.
If I used the Launcher and click the Desktop icon though, I get an error. I think the salient part is:
```
TurboVNC Server (Xvnc) 64-bit v3.1.1 (build 20240127)
Copyright (C) 1999-2024 The VirtualGL Project and many others (see README.md)
Visit http://www.TurboVNC.org for more information on TurboVNC

(EE) 
Fatal server error:
(EE) ERROR: /etc/turbovncserver-security.conf must be owned by you or by root(EE) 
```

Indeed, if I shell into the container and list it i see:
`-rw-r--r--  1 nobody nogroup  4155 Jan 27  2024 turbovncserver-security.conf`
Alas, trying to `chown` it gives:
```
chown: changing ownership of '/etc/turbovncserver-security.conf': Value too large for defined data type
```

Importantly, if I use the TigerVNC one, everything works just fine!

### How to reproduce

1. `apptainer pull docker://quay.io/jupyterhub/jupyter-remote-desktop-proxy:latest-turbovnc`
This work, I get a SIF. 
2. `apptainer run --env JUPYTER_PORT=11008 jupyter-remote-desktop-proxy_latest-turbovnc.sif`
This works, I can connect in the browser
3. connect to Jupyter in the browser and try to launch the Desktop tab
This doesn't work

#### Expected behaviour

I expected it to work just like tigerVNC, but maybe faster with better openGL support -- to be determined.

#### Actual behaviour

The desktop never launches

### Your personal set up

Rocky9
apptainer 1.1.9

**Comment by psobolewskiPhD** [comment]
Hmm, pretty sure this is do to something about apptainer that I don't understand and not related to jupyter-remote-desktop-proxy.
If anyone has any advice for solving it I'd be very appreciative, but otherwise I think this can be closed.

**Comment by manics** [comment]
It definitely sounds like something to do with Apptainer, and not the image.

Try asking on an Apptainer forum, or you could try https://discourse.jupyter.org/ since quite a few Jupyter HPC people hang out there.
