### ISSUE TITLE
desktop transitions to lock screen if left alone.

### ISSUE THREAD

**Issue by satra** [jupyterhub/jupyter-remote-desktop-proxy#17]
### Bug description

the desktop proxy appears to go into a lock screen if left alone. 

#### Expected behaviour

lock screen never appears

#### Actual behaviour

lock screen appears if the system is left alone. or locked explicitly.

### How to reproduce

you can download and run the following docker container launch the desktop and leave it for a while.

### Your personal set up

this is the base docker container: dandiarchive/dandihub:latest

https://github.com/dandi/dandi-hub/blob/dandi/docker/Dockerfile#L40

**Comment by evanlinde** [comment]
When I adjust my XFCE settings (XFCE 4.16 on Rocky Linux 8.7) to disable screen lock, the config file `~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-screensaver.xml` is created or updated. Including this file (with appropriate settings) in the image may resolve this issue.

Here is the minimal content for `xfce4-screensaver.xml` that should disable screen lock:

```
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-screensaver" version="1.0">
  <property name="lock" type="empty">
    <property name="enabled" type="bool" value="false"/>
  </property>
</channel>
```

**Comment by satra** [comment]
thank you. i was able to do this through the graphical interface which generated a few more lines:

```
$ cat ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-screensaver.xml 
<?xml version="1.0" encoding="UTF-8"?>

<channel name="xfce4-screensaver" version="1.0">
  <property name="lock" type="empty">
    <property name="enabled" type="bool" value="false"/>
  </property>
  <property name="saver" type="empty">
    <property name="mode" type="int" value="0"/>
    <property name="enabled" type="bool" value="false"/>
  </property>
</channel>
```
