### ISSUE TITLE
mybinder.org build is broken

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyter-remote-desktop-proxy#26]
### Bug description

The https://mybinder.org/v2/gh/jupyterhub/jupyter-remote-desktop-proxy/HEAD?urlpath=desktop badge fails to launch a working server

#### Expected behaviour

You should end up at a Linux desktop on mybinder.org

#### Actual behaviour
![image](https://user-images.githubusercontent.com/1644105/214013029-a0db4175-76d7-4443-abec-727b486edb03.png)

### How to reproduce

https://mybinder.org/v2/gh/jupyterhub/jupyter-remote-desktop-proxy/HEAD?urlpath=desktop

**Comment by consideRatio** [comment]
I think it works again now, but it took more than one attempt to get it running, but that was related to mybinder.org operations I think.
