### ISSUE TITLE
Repository license is incorrect

### ISSUE THREAD

**Issue by manics** [jupyterhub/jupyter-remote-desktop-proxy#27]
### Bug description

This repository is [licensed under BSD-3-Clause](https://github.com/jupyterhub/jupyter-remote-desktop-proxy/blob/v1.0/LICENSE).

However it bundles and distributes [TigerVNC which is GPL-2.0](https://github.com/TigerVNC/tigervnc):
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/tree/v1.0/jupyter_remote_desktop_proxy/share/tigervnc

#### Expected behaviour

Either:
- Update the license to indicate this bundles third-party binaries under a different license
- Relicense as GPL-2.0
- Don't bundle TigerVNC

**Comment by benz0li** [comment]
Furthermore, the bundled TigerVNC is `x86-64` and will not work on other architectures (e.g. `aarch64`).

The *default* version of this extension, i.e. *without* user installed `vncserver`, is not suitable for multi-arch docker images.

**Comment by manics** [comment]
In addition to the VNCserver we're also bundling a patched version of noVNC which has an MPL 2 licence:
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/blob/v1.2.1/jupyter_remote_desktop_proxy/share/web/noVNC-1.2.0/LICENSE.txt

This package is distributed on PyPI with a BSD licence
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/blob/v1.2.1/setup.py#L17

After reading https://www.mozilla.org/en-US/MPL/2.0/FAQ/ I'm not sure what we have to do. Is it acceptable that the noVNC license is included in the source code, or do we have to update the PyPI metadata to indicate the package includes files under a different licence?

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/77 stops vendoring novnc for this and many other reasons.
