### ISSUE TITLE
TurboVNC broken since commit 447bf86, still in 1.2.1

### ISSUE THREAD

**Issue by benz0li** [jupyterhub/jupyter-remote-desktop-proxy#54]
### Bug description

Commit 447bf86 breaks the use of TurboVNC.

#### Expected behaviour

The image should work whether TigerVNC or TurboVNC is used.

#### Actual behaviour

The image does not work when TurboVNC is used.

### How to reproduce

Build image with TurboVNC installed.

1. Click on 'desktop [↗]'.
2. See error: `Something went wrong, connection is closed`.
3. Check `~/.vnc/<CONTAINER ID>:<DISPLAY NUMBER>.log` for details.

### Your personal set up

 - OS: macOS 13.5.1 + Docker Desktop 4.22.1

See https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/47#issuecomment-1687705198 for logs and additional information.

**Comment by benz0li** [comment]
FYI @nathanin @domna

**Comment by yuvipanda** [comment]
@benz0li I don't have comparative experience about turbovnc vs tigervnc. Was there a specific reason you want to use TurboVNC?

**Comment by benz0li** [comment]
> @benz0li I don't have comparative experience about turbovnc vs tigervnc. Was there a specific reason you want to use TurboVNC?

https://turbovnc.org/About/TigerVNC. Beyond that, there are no particular reasons.

---

I forked this project and keep a separate branch for QGIS that works with TurboVNC (in a container): https://github.com/b-data/jupyter-remote-desktop-proxy/tree/QGIS  
ℹ️ I use this branch in my JupyterLab QGIS docker stack: https://github.com/b-data/jupyterlab-qgis-docker-stack/blob/cab6f444535284bd6bd26d6fe380bc4c46bb55fe/base/Dockerfile#L372

I can adapt everything to my needs.

**Comment by consideRatio** [comment]
This was reported for 1.1.0, we now have 1.2.1 released - is this still an issue?

**Comment by benz0li** [comment]
> This was reported for 1.1.0, we now have 1.2.1 released - is this still an issue?

@consideRatio I will check and give feedback within a week.

**Comment by benz0li** [comment]
@consideRatio Just tested: Still the same issue with v1.2.1.

**Comment by consideRatio** [comment]
Do you have logs available to go with this issue as well?

**Comment by benz0li** [comment]
> Thank you @benz0li for confirming this! Do you have logs available to go with this issue as well?

Still the same. See https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/47#issuecomment-1687705198 ff.

**Comment by benz0li** [comment]
I work around this issue using a fork + reverting 447bf86 (https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/54#issuecomment-1693936668).

And this project uses TigerVNC by default.

So no need to worry.

**Comment by benz0li** [comment]
I have just released a GPU accelerated JupyterLab QGIS image:

![cuda-screenshot](https://github.com/jupyterhub/jupyter-remote-desktop-proxy/assets/20233085/b7934c74-fe14-436f-b257-f7d94abbcd5a)

TurboVNC + VirtualGL = Fully GPU accelerated OpenGL applications  
👉 Requires NVIDIA GPU + NVIDIA Linux driver + NVIDIA Container Toolkit

ℹ️ For more information, see https://github.com/b-data/jupyterlab-qgis-docker-stack/blob/main/CUDA.md

**Comment by benz0li** [comment]
Closed in favour of https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/56 and https://github.com/jupyterhub/jupyter-remote-desktop-proxy/issues/68.

**Comment by consideRatio** [comment]
This is still an issue, but fixed in #99
