### ISSUE TITLE
Add a link to the hub control panel

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/jupyter-remote-desktop-proxy#57]
Currently, there's no way to go back to the hub home page / control panel without modifying the URL. We should instead have a button in the UI that lets people go back home / to JupyterLab launcher.

**Comment by romainrossi** [comment]
I agree, the current behavior sent the user to a new tab with no way to easilly go back to the "main" jupyterlab UI.
I will be interested into integration of the VNC viewer in a tab, like the original NoVNC jupyterlab extention : https://github.com/robostack/jupyterlab-novnc

I tried using the original NoVNC extention to connect to the VNC server but with no success.

**Comment by yuvipanda** [comment]
@romainrossi with #78, you can click the jupyter logo to go back to lab / notebook!

I think it would still be nice to have a separate link to the hub control panel itself.
