### ISSUE TITLE
Password required when running mybinder demo

### ISSUE THREAD

**Issue by psychemedia** [jupyterhub/jupyter-remote-desktop-proxy#75]
What's the password for accessing the desktop when running the MyBinder demo?

<img width="1231" alt="image" src="https://github.com/jupyterhub/jupyter-remote-desktop-proxy/assets/82988/c0cca277-fa41-4dad-bf21-f8a1d57fa43a">

**Comment by manics** [comment]
This is built on top of the standard docker-stacks Jupyter images, so there's no password set. Presumably this is the automatic screensaver/screenlock? If so that will hopefully be stopped by https://github.com/jupyterhub/jupyter-remote-desktop-proxy/pull/76
